### ISSUE TITLE
Allow timing specific files

### ISSUE THREAD

**Issue by jyn514** [hyiltiz/vim-plugins-profile#22]
vim-plug supports on-demand loading, which means that if you just open a blank vim instance, you don't see the time spent to load the lazy plugin. It would be nice to allow timing opening various files, so you can see the difference.

Here's opening an empty file on my machine:
```
$ ruby vim-plugins-profile.rb
Testing vim performance...
Assuming your vimfiles folder is /home/joshua/.vim.
Generating vim startup profile...
vim-plug has been detected.

   vim-gitgutter: (2.919ms) ************************************************************************************************************************
    vim-fugitive: (2.073ms) *************************************************************************************
  vim-autoformat: (1.143ms) **********************************************
       ultisnips: (0.773ms) *******************************
editorconfig-vim: (0.642ms) **************************
     vim-markify: (0.637ms) **************************
  vim-paste-easy: (0.337ms) *************
            rust: (0.069ms) **
            bats: (0.052ms) **
    vim-snippets: (0.046ms) *
        vim-misc: (0.043ms) *
vim-markdown-toc: (0.029ms) *
```

And here's opening a rust file:
```
Testing vim performance...
Assuming your vimfiles folder is /home/joshua/.vim.
Generating vim startup profile...
vim-plug has been detected.

            rust: (26.353ms) ************************************************************************************************************************
   vim-gitgutter: (17.272ms) ******************************************************************************
    vim-fugitive: (7.404ms) *********************************
  vim-autoformat: (0.944ms) ****
editorconfig-vim: (0.71 ms) ***
       ultisnips: (0.596ms) **
     vim-markify: (0.453ms) **
  vim-paste-easy: (0.264ms) *
        vim-misc: (0.052ms) 
    vim-snippets: (0.042ms) 
            bats: (0.029ms) 
vim-markdown-toc: (0.024ms) 
```

Notice the factor of 10 slowdown.

**Comment by hyiltiz** [comment]
Great idea! However, profiling lazy behavior can get a bit tricky. For example, what should the interface look like? Should the user also provide a file to profile against? That wouldn't quite represent performance in general.

**Comment by jyn514** [comment]
Yes, I was imagining that you provide a specific file to profile against.

> That wouldn't quite represent performance in general.

I think it's hard to characterize performance in general in the presense of lazy loading.

**Comment by hyiltiz** [comment]
If you have a good proposal we can work out (is `vim --startuptime $logfile $1` not working?), please feel free; otherwise, do you think it (lazy loading benchmarking is beyond the scope of this project) resolved the issue?

**Comment by hyiltiz** [comment]
I think it may be sufficient to just provide a sentence of documentation on how to call the profiler given a specific file (as you have done above with a `rust` file). Would you like to propose an edit to the `Readme.md`? I'll merge your pull request.
 
I think that is the simplest way to "provide" support for lazy loading. Another extreme is to come up with a bunch of "typical" files but no typical file is relevant to anyone specifically, so that is probably pointless.

**Comment by hyiltiz** [comment]
Shall I close this issue due to inactivity?

**Comment by jyn514** [comment]
Yes, sorry, I don't use vim anymore.
